apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ymoyw1abk-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:cb4f44ea44b1fa89e62bedb516e2a1537f811c79@sha256:8f3a5b3f1e1c5cb92342fe4f02940ca7fbb3a63939dd8a5c72582b909fcd33d9
          name: container-image
